# Generated by Django 5.1.3 on 2025-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
