# Generated by Django 5.1.3 on 2025-07-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'CategoryModel',
                'verbose_name_plural': 'CategoryModels',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='PostingTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'PostingTypeModel',
                'verbose_name_plural': 'PostingTypeModels',
                'db_table': 'posting',
            },
        ),
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(verbose_name='Manzil')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('contact_time', models.CharField(max_length=50, verbose_name='Murojat vaqti')),
                ('specialty', models.CharField(max_length=300, verbose_name='Mutaxasislik')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('image', models.ImageField(upload_to='listing/', verbose_name='Rasm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorymodel')),
                ('posting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='api.postingtypemodel', verbose_name='Elon turi')),
            ],
            options={
                'verbose_name': 'ListingModel',
                'verbose_name_plural': 'ListingModels',
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='ListingimageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.listingmodel')),
            ],
            options={
                'verbose_name': 'ListingimageModel',
                'verbose_name_plural': 'ListingimageModels',
                'db_table': 'listingImage',
            },
        ),
    ]
