# Generated by Django 5.1.3 on 2025-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'FeatureModel',
                'verbose_name_plural': 'FeatureModels',
                'db_table': 'feature',
            },
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='postingtypemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='bio',
            field=models.TextField(default=1, verbose_name='Bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='phone',
            field=models.CharField(default=1, max_length=100, verbose_name='Telefon raqam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='telegram',
            field=models.CharField(default=1, max_length=200, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postingtypemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postingtypemodel',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='posting_type',
            field=models.CharField(max_length=300, verbose_name='Mutaxasislik'),
        ),
        migrations.AddField(
            model_name='postingtypemodel',
            name='feature',
            field=models.ManyToManyField(blank=True, to='api.featuremodel', verbose_name='Xususiyatlar'),
        ),
    ]
