# Generated by Django 5.1.3 on 2025-07-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_featuremodel_remove_listingmodel_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='specialty',
            field=models.CharField(default=1, max_length=300, verbose_name='Mutaxasislik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='posting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='api.postingtypemodel', verbose_name='Elon turi'),
        ),
    ]
